export const latest_jobs = {
    latest:[
        {   job_id: 1,
            category: 'IT',
            sub_category: 'Web development',
            image_url : 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAACB0lEQVR4AcXUA4wkURSF4Y65tl1oozQK17Zt70Zr27Zt2wjWts0xYt3hGbW7MJ386fh8hVem/fVFmlfOSUsqOGh1JQdtrOKk7VWdtK+6iw7XcNHx2k46V8dNl+q56UZWtxu46G4jgR4yAj1mPfSC89BrXqD3vIc+WUT6bBHou1WkHzaB/tgl+msX6J9DpHiHRIlZ/0lOCVFat16C6VQtGx3jFMMBySPG2U3Zv2xAdgfrC4YB0jt0UXLGAUDnrNG6A9IWrmiI7SIAdKyBoBvgf9u20dj1CUCn+WjNARkTp5uxGRiAGFkzQFK3bgr2QgKgM4ysGpDab7AbW2EB0FlWjhiQ0GeggJ2IAOgcI4UN+NUaR00lAF2wxoYMSBozGS+cRgAgGCko4HeLjjhqGgOAsMT4BSQsX854L2gIQJc52QvwCVeuOwAIswIAfRs6HkfNGAC6xiv0sUtfvO3GA7Y2iqWlfItpJQLY20ChKaXtOa10tl1kKGBHXRHjiJZwTaYYAtjHxXmNo7VK13W6ArbXwZX7bxHXbIougH2NooOOo2Wudgs0BeysI4U8jpbwzadpAthdTw57HC23tpyhCrC7fuTjaIWj9ZyIADtx1DRoEdt0WlgAvHBatkrotCIkwA4cNR1azDWdFBBwgI1VORLBnVB/5SreCQB2N4wybNzrdOzEOTc4fCcyASRu7AlXUGPrAAAAAElFTkSuQmCC', 
            salary : 3000, 
            skills: ["Node.js", "Express", "git", "Github", "php", "js", "Node.js", "Express", "git", "Github", "php", "js", "Node.js", "Express", "git", "Github", "php", "js"],
            job_experience: "3 ildən 5 ilə qədər",
            education: 'Ali',
            age: 21,
            special_requirements: ['Professional experience building responsive, user friendly web applications;', 'Deep understanding of modern JavaScript, Typescript & browser APIs', 'Proficiency with ReactJS and it’s ecosystem, Styled components, Webpack module bundler', 'Understanding of how software is developed, code quality principles & testing techniques', 'Proficiency in CSS pre-processing platform', 'Experience collaborating on software projects with design and backend aspects'],
            job_description: 'Front-end developer kimi siz müştəri tələblərini cəlbedici, istifadəsi asan və interaktiv platformalara çevirmək bacarığına malik olmalısınız. Siz istifadəçi ilə bağlı yeni funksiyaların işlənib hazırlanmasına, veb səhifələrin strukturunun və dizaynının müəyyən edilməsinə, təkrar istifadə edilə bilən kodların qurulmasına, səhifə yükləmə vaxtlarının optimallaşdırılmasına və veb səhifələri yaratmaq üçün müxtəlif işarələmə dillərindən istifadə etməyə cavabdeh olacaqsınız.',
            job_title : 'Backend developer', 
            company_name : 'Kapital bank', 
            post_views : 1000,
            post_applies: 1000, 
            post_start_date : "27.03.2023", 
            post_end_date : "20.04.2023", 
            location : "Bakı", 
            job_time_type : "Tam iş günü"
        },
        {   job_id: 2,
            category: 'IT',
            sub_category: 'Web development',
            image_url : 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAACB0lEQVR4AcXUA4wkURSF4Y65tl1oozQK17Zt70Zr27Zt2wjWts0xYt3hGbW7MJ386fh8hVem/fVFmlfOSUsqOGh1JQdtrOKk7VWdtK+6iw7XcNHx2k46V8dNl+q56UZWtxu46G4jgR4yAj1mPfSC89BrXqD3vIc+WUT6bBHou1WkHzaB/tgl+msX6J9DpHiHRIlZ/0lOCVFat16C6VQtGx3jFMMBySPG2U3Zv2xAdgfrC4YB0jt0UXLGAUDnrNG6A9IWrmiI7SIAdKyBoBvgf9u20dj1CUCn+WjNARkTp5uxGRiAGFkzQFK3bgr2QgKgM4ysGpDab7AbW2EB0FlWjhiQ0GeggJ2IAOgcI4UN+NUaR00lAF2wxoYMSBozGS+cRgAgGCko4HeLjjhqGgOAsMT4BSQsX854L2gIQJc52QvwCVeuOwAIswIAfRs6HkfNGAC6xiv0sUtfvO3GA7Y2iqWlfItpJQLY20ChKaXtOa10tl1kKGBHXRHjiJZwTaYYAtjHxXmNo7VK13W6ArbXwZX7bxHXbIougH2NooOOo2Wudgs0BeysI4U8jpbwzadpAthdTw57HC23tpyhCrC7fuTjaIWj9ZyIADtx1DRoEdt0WlgAvHBatkrotCIkwA4cNR1azDWdFBBwgI1VORLBnVB/5SreCQB2N4wybNzrdOzEOTc4fCcyASRu7AlXUGPrAAAAAElFTkSuQmCC', 
            salary : 3000, 
            skills: ["Node.js", "Express", "git", "Github", "php", "js"],
            job_experience: "3 ildən 5 ilə qədər",
            education: 'Ali',
            age: 21,
            special_requirements: ['Professional experience building responsive, user friendly web applications;', 'Deep understanding of modern JavaScript, Typescript & browser APIs', 'Proficiency with ReactJS and it’s ecosystem, Styled components, Webpack module bundler', 'Understanding of how software is developed, code quality principles & testing techniques', 'Proficiency in CSS pre-processing platform', 'Experience collaborating on software projects with design and backend aspects'],
            job_description: 'Front-end developer kimi siz müştəri tələblərini cəlbedici, istifadəsi asan və interaktiv platformalara çevirmək bacarığına malik olmalısınız. Siz istifadəçi ilə bağlı yeni funksiyaların işlənib hazırlanmasına, veb səhifələrin strukturunun və dizaynının müəyyən edilməsinə, təkrar istifadə edilə bilən kodların qurulmasına, səhifə yükləmə vaxtlarının optimallaşdırılmasına və veb səhifələri yaratmaq üçün müxtəlif işarələmə dillərindən istifadə etməyə cavabdeh olacaqsınız.',
            job_title : 'Frontend developer', 
            company_name : 'Kapital bank', 
            post_views : 1000,
            post_applies: 1000, 
            post_start_date : "27.03.2023", 
            post_end_date : "20.04.2023", 
            location : "Bakı", 
            job_time_type : "Tam iş günü"
        },
        {   job_id: 3,
            category: 'IT',
            sub_category: 'Web development',
            image_url : 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAACB0lEQVR4AcXUA4wkURSF4Y65tl1oozQK17Zt70Zr27Zt2wjWts0xYt3hGbW7MJ386fh8hVem/fVFmlfOSUsqOGh1JQdtrOKk7VWdtK+6iw7XcNHx2k46V8dNl+q56UZWtxu46G4jgR4yAj1mPfSC89BrXqD3vIc+WUT6bBHou1WkHzaB/tgl+msX6J9DpHiHRIlZ/0lOCVFat16C6VQtGx3jFMMBySPG2U3Zv2xAdgfrC4YB0jt0UXLGAUDnrNG6A9IWrmiI7SIAdKyBoBvgf9u20dj1CUCn+WjNARkTp5uxGRiAGFkzQFK3bgr2QgKgM4ysGpDab7AbW2EB0FlWjhiQ0GeggJ2IAOgcI4UN+NUaR00lAF2wxoYMSBozGS+cRgAgGCko4HeLjjhqGgOAsMT4BSQsX854L2gIQJc52QvwCVeuOwAIswIAfRs6HkfNGAC6xiv0sUtfvO3GA7Y2iqWlfItpJQLY20ChKaXtOa10tl1kKGBHXRHjiJZwTaYYAtjHxXmNo7VK13W6ArbXwZX7bxHXbIougH2NooOOo2Wudgs0BeysI4U8jpbwzadpAthdTw57HC23tpyhCrC7fuTjaIWj9ZyIADtx1DRoEdt0WlgAvHBatkrotCIkwA4cNR1azDWdFBBwgI1VORLBnVB/5SreCQB2N4wybNzrdOzEOTc4fCcyASRu7AlXUGPrAAAAAElFTkSuQmCC', 
            salary : 3000, 
            skills: ["Node.js", "Express", "git", "Github", "php", "js"],
            job_experience: "3 ildən 5 ilə qədər",
            education: 'Ali',
            age: 21,
            special_requirements: ['Professional experience building responsive, user friendly web applications;', 'Deep understanding of modern JavaScript, Typescript & browser APIs', 'Proficiency with ReactJS and it’s ecosystem, Styled components, Webpack module bundler', 'Understanding of how software is developed, code quality principles & testing techniques', 'Proficiency in CSS pre-processing platform', 'Experience collaborating on software projects with design and backend aspects'],
            job_description: 'Front-end developer kimi siz müştəri tələblərini cəlbedici, istifadəsi asan və interaktiv platformalara çevirmək bacarığına malik olmalısınız. Siz istifadəçi ilə bağlı yeni funksiyaların işlənib hazırlanmasına, veb səhifələrin strukturunun və dizaynının müəyyən edilməsinə, təkrar istifadə edilə bilən kodların qurulmasına, səhifə yükləmə vaxtlarının optimallaşdırılmasına və veb səhifələri yaratmaq üçün müxtəlif işarələmə dillərindən istifadə etməyə cavabdeh olacaqsınız.',
            job_title : 'QA engineer', 
            company_name : 'Kapital bank', 
            post_views : 1000,
            post_applies: 1000, 
            post_start_date : "27.03.2023", 
            post_end_date : "20.04.2023", 
            location : "Bakı", 
            job_time_type : "Tam iş günü"
        },
        {   job_id: 4,
            category: 'IT',
            sub_category: 'Web development',
            image_url : 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAACB0lEQVR4AcXUA4wkURSF4Y65tl1oozQK17Zt70Zr27Zt2wjWts0xYt3hGbW7MJ386fh8hVem/fVFmlfOSUsqOGh1JQdtrOKk7VWdtK+6iw7XcNHx2k46V8dNl+q56UZWtxu46G4jgR4yAj1mPfSC89BrXqD3vIc+WUT6bBHou1WkHzaB/tgl+msX6J9DpHiHRIlZ/0lOCVFat16C6VQtGx3jFMMBySPG2U3Zv2xAdgfrC4YB0jt0UXLGAUDnrNG6A9IWrmiI7SIAdKyBoBvgf9u20dj1CUCn+WjNARkTp5uxGRiAGFkzQFK3bgr2QgKgM4ysGpDab7AbW2EB0FlWjhiQ0GeggJ2IAOgcI4UN+NUaR00lAF2wxoYMSBozGS+cRgAgGCko4HeLjjhqGgOAsMT4BSQsX854L2gIQJc52QvwCVeuOwAIswIAfRs6HkfNGAC6xiv0sUtfvO3GA7Y2iqWlfItpJQLY20ChKaXtOa10tl1kKGBHXRHjiJZwTaYYAtjHxXmNo7VK13W6ArbXwZX7bxHXbIougH2NooOOo2Wudgs0BeysI4U8jpbwzadpAthdTw57HC23tpyhCrC7fuTjaIWj9ZyIADtx1DRoEdt0WlgAvHBatkrotCIkwA4cNR1azDWdFBBwgI1VORLBnVB/5SreCQB2N4wybNzrdOzEOTc4fCcyASRu7AlXUGPrAAAAAElFTkSuQmCC', 
            salary : 3000, 
            skills: ["Node.js", "Express", "git", "Github", "php", "js"],
            job_experience: "3 ildən 5 ilə qədər",
            education: 'Ali',
            age: 21,
            special_requirements: ['Professional experience building responsive, user friendly web applications;', 'Deep understanding of modern JavaScript, Typescript & browser APIs', 'Proficiency with ReactJS and it’s ecosystem, Styled components, Webpack module bundler', 'Understanding of how software is developed, code quality principles & testing techniques', 'Proficiency in CSS pre-processing platform', 'Experience collaborating on software projects with design and backend aspects'],
            job_description: 'Front-end developer kimi siz müştəri tələblərini cəlbedici, istifadəsi asan və interaktiv platformalara çevirmək bacarığına malik olmalısınız. Siz istifadəçi ilə bağlı yeni funksiyaların işlənib hazırlanmasına, veb səhifələrin strukturunun və dizaynının müəyyən edilməsinə, təkrar istifadə edilə bilən kodların qurulmasına, səhifə yükləmə vaxtlarının optimallaşdırılmasına və veb səhifələri yaratmaq üçün müxtəlif işarələmə dillərindən istifadə etməyə cavabdeh olacaqsınız.',
            job_title : 'Full stack developer', 
            company_name : 'Kapital bank', 
            post_views : 1000,
            post_applies: 1000, 
            post_start_date : "27.03.2023", 
            post_end_date : "20.04.2023", 
            location : "Bakı", 
            job_time_type : "Tam iş günü"
        },
        {   job_id: 5,
            category: 'IT',
            sub_category: 'Web development',
            image_url : 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAACB0lEQVR4AcXUA4wkURSF4Y65tl1oozQK17Zt70Zr27Zt2wjWts0xYt3hGbW7MJ386fh8hVem/fVFmlfOSUsqOGh1JQdtrOKk7VWdtK+6iw7XcNHx2k46V8dNl+q56UZWtxu46G4jgR4yAj1mPfSC89BrXqD3vIc+WUT6bBHou1WkHzaB/tgl+msX6J9DpHiHRIlZ/0lOCVFat16C6VQtGx3jFMMBySPG2U3Zv2xAdgfrC4YB0jt0UXLGAUDnrNG6A9IWrmiI7SIAdKyBoBvgf9u20dj1CUCn+WjNARkTp5uxGRiAGFkzQFK3bgr2QgKgM4ysGpDab7AbW2EB0FlWjhiQ0GeggJ2IAOgcI4UN+NUaR00lAF2wxoYMSBozGS+cRgAgGCko4HeLjjhqGgOAsMT4BSQsX854L2gIQJc52QvwCVeuOwAIswIAfRs6HkfNGAC6xiv0sUtfvO3GA7Y2iqWlfItpJQLY20ChKaXtOa10tl1kKGBHXRHjiJZwTaYYAtjHxXmNo7VK13W6ArbXwZX7bxHXbIougH2NooOOo2Wudgs0BeysI4U8jpbwzadpAthdTw57HC23tpyhCrC7fuTjaIWj9ZyIADtx1DRoEdt0WlgAvHBatkrotCIkwA4cNR1azDWdFBBwgI1VORLBnVB/5SreCQB2N4wybNzrdOzEOTc4fCcyASRu7AlXUGPrAAAAAElFTkSuQmCC', 
            salary : 3000, 
            skills: ["Node.js", "Express", "git", "Github", "php", "js"],
            job_experience: "3 ildən 5 ilə qədər",
            education: 'Ali',
            age: 21,
            special_requirements: ['Professional experience building responsive, user friendly web applications;', 'Deep understanding of modern JavaScript, Typescript & browser APIs', 'Proficiency with ReactJS and it’s ecosystem, Styled components, Webpack module bundler', 'Understanding of how software is developed, code quality principles & testing techniques', 'Proficiency in CSS pre-processing platform', 'Experience collaborating on software projects with design and backend aspects'],
            job_description: 'Front-end developer kimi siz müştəri tələblərini cəlbedici, istifadəsi asan və interaktiv platformalara çevirmək bacarığına malik olmalısınız. Siz istifadəçi ilə bağlı yeni funksiyaların işlənib hazırlanmasına, veb səhifələrin strukturunun və dizaynının müəyyən edilməsinə, təkrar istifadə edilə bilən kodların qurulmasına, səhifə yükləmə vaxtlarının optimallaşdırılmasına və veb səhifələri yaratmaq üçün müxtəlif işarələmə dillərindən istifadə etməyə cavabdeh olacaqsınız.',
            job_title : 'Backend developer', 
            company_name : 'Kapital bank', 
            post_views : 1000,
            post_applies: 1000, 
            post_start_date : "27.03.2023", 
            post_end_date : "20.04.2023", 
            location : "Bakı", 
            job_time_type : "Tam iş günü"
        },
        {   job_id: 6,
            category: 'IT',
            sub_category: 'Web development',
            image_url : 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAACB0lEQVR4AcXUA4wkURSF4Y65tl1oozQK17Zt70Zr27Zt2wjWts0xYt3hGbW7MJ386fh8hVem/fVFmlfOSUsqOGh1JQdtrOKk7VWdtK+6iw7XcNHx2k46V8dNl+q56UZWtxu46G4jgR4yAj1mPfSC89BrXqD3vIc+WUT6bBHou1WkHzaB/tgl+msX6J9DpHiHRIlZ/0lOCVFat16C6VQtGx3jFMMBySPG2U3Zv2xAdgfrC4YB0jt0UXLGAUDnrNG6A9IWrmiI7SIAdKyBoBvgf9u20dj1CUCn+WjNARkTp5uxGRiAGFkzQFK3bgr2QgKgM4ysGpDab7AbW2EB0FlWjhiQ0GeggJ2IAOgcI4UN+NUaR00lAF2wxoYMSBozGS+cRgAgGCko4HeLjjhqGgOAsMT4BSQsX854L2gIQJc52QvwCVeuOwAIswIAfRs6HkfNGAC6xiv0sUtfvO3GA7Y2iqWlfItpJQLY20ChKaXtOa10tl1kKGBHXRHjiJZwTaYYAtjHxXmNo7VK13W6ArbXwZX7bxHXbIougH2NooOOo2Wudgs0BeysI4U8jpbwzadpAthdTw57HC23tpyhCrC7fuTjaIWj9ZyIADtx1DRoEdt0WlgAvHBatkrotCIkwA4cNR1azDWdFBBwgI1VORLBnVB/5SreCQB2N4wybNzrdOzEOTc4fCcyASRu7AlXUGPrAAAAAElFTkSuQmCC', 
            salary : 3000, 
            skills: ["Node.js", "Express", "git", "Github", "php", "js"],
            job_experience: "3 ildən 5 ilə qədər",
            education: 'Ali',
            age: 21,
            special_requirements: ['Professional experience building responsive, user friendly web applications;', 'Deep understanding of modern JavaScript, Typescript & browser APIs', 'Proficiency with ReactJS and it’s ecosystem, Styled components, Webpack module bundler', 'Understanding of how software is developed, code quality principles & testing techniques', 'Proficiency in CSS pre-processing platform', 'Experience collaborating on software projects with design and backend aspects'],
            job_description: 'Front-end developer kimi siz müştəri tələblərini cəlbedici, istifadəsi asan və interaktiv platformalara çevirmək bacarığına malik olmalısınız. Siz istifadəçi ilə bağlı yeni funksiyaların işlənib hazırlanmasına, veb səhifələrin strukturunun və dizaynının müəyyən edilməsinə, təkrar istifadə edilə bilən kodların qurulmasına, səhifə yükləmə vaxtlarının optimallaşdırılmasına və veb səhifələri yaratmaq üçün müxtəlif işarələmə dillərindən istifadə etməyə cavabdeh olacaqsınız.',
            job_title : 'Frontend developer', 
            company_name : 'Kapital bank', 
            post_views : 1000,
            post_applies: 1000, 
            post_start_date : "27.03.2023", 
            post_end_date : "20.04.2023", 
            location : "Bakı", 
            job_time_type : "Tam iş günü"
        },
        {   job_id: 7,
            category: 'IT',
            sub_category: 'Web development',
            image_url : 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAACB0lEQVR4AcXUA4wkURSF4Y65tl1oozQK17Zt70Zr27Zt2wjWts0xYt3hGbW7MJ386fh8hVem/fVFmlfOSUsqOGh1JQdtrOKk7VWdtK+6iw7XcNHx2k46V8dNl+q56UZWtxu46G4jgR4yAj1mPfSC89BrXqD3vIc+WUT6bBHou1WkHzaB/tgl+msX6J9DpHiHRIlZ/0lOCVFat16C6VQtGx3jFMMBySPG2U3Zv2xAdgfrC4YB0jt0UXLGAUDnrNG6A9IWrmiI7SIAdKyBoBvgf9u20dj1CUCn+WjNARkTp5uxGRiAGFkzQFK3bgr2QgKgM4ysGpDab7AbW2EB0FlWjhiQ0GeggJ2IAOgcI4UN+NUaR00lAF2wxoYMSBozGS+cRgAgGCko4HeLjjhqGgOAsMT4BSQsX854L2gIQJc52QvwCVeuOwAIswIAfRs6HkfNGAC6xiv0sUtfvO3GA7Y2iqWlfItpJQLY20ChKaXtOa10tl1kKGBHXRHjiJZwTaYYAtjHxXmNo7VK13W6ArbXwZX7bxHXbIougH2NooOOo2Wudgs0BeysI4U8jpbwzadpAthdTw57HC23tpyhCrC7fuTjaIWj9ZyIADtx1DRoEdt0WlgAvHBatkrotCIkwA4cNR1azDWdFBBwgI1VORLBnVB/5SreCQB2N4wybNzrdOzEOTc4fCcyASRu7AlXUGPrAAAAAElFTkSuQmCC', 
            salary : 3000, 
            skills: ["Node.js", "Express", "git", "Github", "php", "js"],
            job_experience: "3 ildən 5 ilə qədər",
            education: 'Ali',
            age: 21,
            special_requirements: ['Professional experience building responsive, user friendly web applications;', 'Deep understanding of modern JavaScript, Typescript & browser APIs', 'Proficiency with ReactJS and it’s ecosystem, Styled components, Webpack module bundler', 'Understanding of how software is developed, code quality principles & testing techniques', 'Proficiency in CSS pre-processing platform', 'Experience collaborating on software projects with design and backend aspects'],
            job_description: 'Front-end developer kimi siz müştəri tələblərini cəlbedici, istifadəsi asan və interaktiv platformalara çevirmək bacarığına malik olmalısınız. Siz istifadəçi ilə bağlı yeni funksiyaların işlənib hazırlanmasına, veb səhifələrin strukturunun və dizaynının müəyyən edilməsinə, təkrar istifadə edilə bilən kodların qurulmasına, səhifə yükləmə vaxtlarının optimallaşdırılmasına və veb səhifələri yaratmaq üçün müxtəlif işarələmə dillərindən istifadə etməyə cavabdeh olacaqsınız.',
            job_title : 'Senior Frontend developer', 
            company_name : 'Kapital bank', 
            post_views : 1000,
            post_applies: 1000, 
            post_start_date : "27.03.2023", 
            post_end_date : "20.04.2023", 
            location : "Bakı", 
            job_time_type : "Tam iş günü"
        },
        {   job_id: 8,
            category: 'IT',
            sub_category: 'Web development',
            image_url : 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAACB0lEQVR4AcXUA4wkURSF4Y65tl1oozQK17Zt70Zr27Zt2wjWts0xYt3hGbW7MJ386fh8hVem/fVFmlfOSUsqOGh1JQdtrOKk7VWdtK+6iw7XcNHx2k46V8dNl+q56UZWtxu46G4jgR4yAj1mPfSC89BrXqD3vIc+WUT6bBHou1WkHzaB/tgl+msX6J9DpHiHRIlZ/0lOCVFat16C6VQtGx3jFMMBySPG2U3Zv2xAdgfrC4YB0jt0UXLGAUDnrNG6A9IWrmiI7SIAdKyBoBvgf9u20dj1CUCn+WjNARkTp5uxGRiAGFkzQFK3bgr2QgKgM4ysGpDab7AbW2EB0FlWjhiQ0GeggJ2IAOgcI4UN+NUaR00lAF2wxoYMSBozGS+cRgAgGCko4HeLjjhqGgOAsMT4BSQsX854L2gIQJc52QvwCVeuOwAIswIAfRs6HkfNGAC6xiv0sUtfvO3GA7Y2iqWlfItpJQLY20ChKaXtOa10tl1kKGBHXRHjiJZwTaYYAtjHxXmNo7VK13W6ArbXwZX7bxHXbIougH2NooOOo2Wudgs0BeysI4U8jpbwzadpAthdTw57HC23tpyhCrC7fuTjaIWj9ZyIADtx1DRoEdt0WlgAvHBatkrotCIkwA4cNR1azDWdFBBwgI1VORLBnVB/5SreCQB2N4wybNzrdOzEOTc4fCcyASRu7AlXUGPrAAAAAElFTkSuQmCC', 
            salary : 3000, 
            skills: ["Node.js", "Express", "git", "Github", "php", "js"],
            job_experience: "3 ildən 5 ilə qədər",
            education: 'Ali',
            age: 21,
            special_requirements: ['Professional experience building responsive, user friendly web applications;', 'Deep understanding of modern JavaScript, Typescript & browser APIs', 'Proficiency with ReactJS and it’s ecosystem, Styled components, Webpack module bundler', 'Understanding of how software is developed, code quality principles & testing techniques', 'Proficiency in CSS pre-processing platform', 'Experience collaborating on software projects with design and backend aspects'],
            job_description: 'Front-end developer kimi siz müştəri tələblərini cəlbedici, istifadəsi asan və interaktiv platformalara çevirmək bacarığına malik olmalısınız. Siz istifadəçi ilə bağlı yeni funksiyaların işlənib hazırlanmasına, veb səhifələrin strukturunun və dizaynının müəyyən edilməsinə, təkrar istifadə edilə bilən kodların qurulmasına, səhifə yükləmə vaxtlarının optimallaşdırılmasına və veb səhifələri yaratmaq üçün müxtəlif işarələmə dillərindən istifadə etməyə cavabdeh olacaqsınız.',
            job_title : 'QA engineer', 
            company_name : 'Kapital bank', 
            post_views : 1000,
            post_applies: 1000, 
            post_start_date : "27.03.2023", 
            post_end_date : "20.04.2023", 
            location : "Bakı", 
            job_time_type : "Tam iş günü"
        },
        {   job_id: 9,
            category: 'IT',
            sub_category: 'Web development',
            image_url : 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAACB0lEQVR4AcXUA4wkURSF4Y65tl1oozQK17Zt70Zr27Zt2wjWts0xYt3hGbW7MJ386fh8hVem/fVFmlfOSUsqOGh1JQdtrOKk7VWdtK+6iw7XcNHx2k46V8dNl+q56UZWtxu46G4jgR4yAj1mPfSC89BrXqD3vIc+WUT6bBHou1WkHzaB/tgl+msX6J9DpHiHRIlZ/0lOCVFat16C6VQtGx3jFMMBySPG2U3Zv2xAdgfrC4YB0jt0UXLGAUDnrNG6A9IWrmiI7SIAdKyBoBvgf9u20dj1CUCn+WjNARkTp5uxGRiAGFkzQFK3bgr2QgKgM4ysGpDab7AbW2EB0FlWjhiQ0GeggJ2IAOgcI4UN+NUaR00lAF2wxoYMSBozGS+cRgAgGCko4HeLjjhqGgOAsMT4BSQsX854L2gIQJc52QvwCVeuOwAIswIAfRs6HkfNGAC6xiv0sUtfvO3GA7Y2iqWlfItpJQLY20ChKaXtOa10tl1kKGBHXRHjiJZwTaYYAtjHxXmNo7VK13W6ArbXwZX7bxHXbIougH2NooOOo2Wudgs0BeysI4U8jpbwzadpAthdTw57HC23tpyhCrC7fuTjaIWj9ZyIADtx1DRoEdt0WlgAvHBatkrotCIkwA4cNR1azDWdFBBwgI1VORLBnVB/5SreCQB2N4wybNzrdOzEOTc4fCcyASRu7AlXUGPrAAAAAElFTkSuQmCC', 
            salary : 3000, 
            skills: ["Node.js", "Express", "git", "Github", "php", "js"],
            job_experience: "3 ildən 5 ilə qədər",
            education: 'Ali',
            age: 21,
            special_requirements: ['Professional experience building responsive, user friendly web applications;', 'Deep understanding of modern JavaScript, Typescript & browser APIs', 'Proficiency with ReactJS and it’s ecosystem, Styled components, Webpack module bundler', 'Understanding of how software is developed, code quality principles & testing techniques', 'Proficiency in CSS pre-processing platform', 'Experience collaborating on software projects with design and backend aspects'],
            job_description: 'Front-end developer kimi siz müştəri tələblərini cəlbedici, istifadəsi asan və interaktiv platformalara çevirmək bacarığına malik olmalısınız. Siz istifadəçi ilə bağlı yeni funksiyaların işlənib hazırlanmasına, veb səhifələrin strukturunun və dizaynının müəyyən edilməsinə, təkrar istifadə edilə bilən kodların qurulmasına, səhifə yükləmə vaxtlarının optimallaşdırılmasına və veb səhifələri yaratmaq üçün müxtəlif işarələmə dillərindən istifadə etməyə cavabdeh olacaqsınız.',
            job_title : 'Junior Mern stack developer', 
            company_name : 'Kapital bank', 
            post_views : 1000,
            post_applies: 1000, 
            post_start_date : "27.03.2023", 
            post_end_date : "20.04.2023", 
            location : "Bakı", 
            job_time_type : "Tam iş günü"
        },
        {   job_id: 10,
            category: 'IT',
            sub_category: 'Web development',
            image_url : 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAACB0lEQVR4AcXUA4wkURSF4Y65tl1oozQK17Zt70Zr27Zt2wjWts0xYt3hGbW7MJ386fh8hVem/fVFmlfOSUsqOGh1JQdtrOKk7VWdtK+6iw7XcNHx2k46V8dNl+q56UZWtxu46G4jgR4yAj1mPfSC89BrXqD3vIc+WUT6bBHou1WkHzaB/tgl+msX6J9DpHiHRIlZ/0lOCVFat16C6VQtGx3jFMMBySPG2U3Zv2xAdgfrC4YB0jt0UXLGAUDnrNG6A9IWrmiI7SIAdKyBoBvgf9u20dj1CUCn+WjNARkTp5uxGRiAGFkzQFK3bgr2QgKgM4ysGpDab7AbW2EB0FlWjhiQ0GeggJ2IAOgcI4UN+NUaR00lAF2wxoYMSBozGS+cRgAgGCko4HeLjjhqGgOAsMT4BSQsX854L2gIQJc52QvwCVeuOwAIswIAfRs6HkfNGAC6xiv0sUtfvO3GA7Y2iqWlfItpJQLY20ChKaXtOa10tl1kKGBHXRHjiJZwTaYYAtjHxXmNo7VK13W6ArbXwZX7bxHXbIougH2NooOOo2Wudgs0BeysI4U8jpbwzadpAthdTw57HC23tpyhCrC7fuTjaIWj9ZyIADtx1DRoEdt0WlgAvHBatkrotCIkwA4cNR1azDWdFBBwgI1VORLBnVB/5SreCQB2N4wybNzrdOzEOTc4fCcyASRu7AlXUGPrAAAAAElFTkSuQmCC', 
            salary : 3000, 
            skills: ["Node.js", "Express", "git", "Github", "php", "js"],
            job_experience: "3 ildən 5 ilə qədər",
            education: 'Ali',
            age: 21,
            special_requirements: ['Professional experience building responsive, user friendly web applications;', 'Deep understanding of modern JavaScript, Typescript & browser APIs', 'Proficiency with ReactJS and it’s ecosystem, Styled components, Webpack module bundler', 'Understanding of how software is developed, code quality principles & testing techniques', 'Proficiency in CSS pre-processing platform', 'Experience collaborating on software projects with design and backend aspects'],
            job_description: 'Front-end developer kimi siz müştəri tələblərini cəlbedici, istifadəsi asan və interaktiv platformalara çevirmək bacarığına malik olmalısınız. Siz istifadəçi ilə bağlı yeni funksiyaların işlənib hazırlanmasına, veb səhifələrin strukturunun və dizaynının müəyyən edilməsinə, təkrar istifadə edilə bilən kodların qurulmasına, səhifə yükləmə vaxtlarının optimallaşdırılmasına və veb səhifələri yaratmaq üçün müxtəlif işarələmə dillərindən istifadə etməyə cavabdeh olacaqsınız.',
            job_title : 'Junior security engineer', 
            company_name : 'Kapital bank', 
            post_views : 1000,
            post_applies: 1000, 
            post_start_date : "27.03.2023", 
            post_end_date : "20.04.2023", 
            location : "Bakı", 
            job_time_type : "Tam iş günü"
        }
    ]       
}